/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Convert PLCopen XML to Markdown. */
export declare function convertXml(xml: string): string
/** Convert Mitsubishi mnemonic format to Markdown. */
export declare function convertMnemonic(mnemonic: string): string
/** Convert Mitsubishi mnemonic to PLCopen XML. */
export declare function mnemonicToXml(mnemonic: string): string
/** Convert PLCopen XML to Mitsubishi mnemonic format. */
export declare function xmlToMnemonic(xml: string): string
/** Result of roundtrip validation. */
export interface ValidationResult {
  parseOk: boolean
  roundtripOk: boolean
  totalRungs: number
  contacts: number
  coils: number
  blocks: number
  errors: Array<string>
}
/** Validate roundtrip conversion of PLCopen XML. */
export declare function validate(xml: string): ValidationResult
